webpack_encore:
    output_path: '%kernel.project_dir%/public/build/default'
    builds:
        bootstrapTheme: '%kernel.project_dir%/public/bootstrap-theme'
        shop: '%kernel.project_dir%/public/build/shop'
        admin: '%kernel.project_dir%/public/build/admin'