version: '3.4'

services:
    mariadb-service:
        image: mariadb
        restart: always
        container_name: mariadb-container
        ports:
            - "3306:3306"
        environment:
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ALLOW_EMPTY_PASSWORD: null
        volumes: 
            - /var/lib/mysql:/var/lib/mysql

    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest
        environment:
        - MH_STORAGE=maildir
        # volumes:
        #   - ./docker/mailhog/maildir:/maildir:rw,delegated
        ports:
        - "8025:8025"

volumes:
  mysql-data:
  public-media:
