app_seller_product_index:
  path: /
  methods: [GET]
  defaults:
      _controller: sylius.controller.product:indexAction
      _sylius:
          template: 'seller/product/index.html.twig'
          grid: app_seller_product
          criteria: 
            store: resource.store #ToDo
      paginate: true
      limit: 100

app_seller_product_create:
  path: /new
  methods: [GET, POST]
  defaults:
      _controller: sylius.controller.product:createAction
      _sylius:
          permission: false
          section: seller
          template: "seller/product/create.html.twig"
          redirect: app_seller_product_index 
          vars:
              subheader: sylius.ui.manage_your_product_catalog
              templates:
                  form: "@SyliusAdmin/Product/_form.html.twig"
              index:
                route: 
                  name: app_seller_product_index
              route: 
                name: app_seller_product_create

app_seller_product_create_simple:
    path: /new/simple
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            section: seller
            permission: false
            factory:
                method: createWithVariant
            template: "seller/product/create.html.twig"
            redirect: app_seller_product_index
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                templates:
                    form: "@SyliusAdmin/Product/_form.html.twig"
                route: 
                  name: app_seller_product_create_simple
                index:
                  route: 
                    name: app_seller_product_index

app_seller_product_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            template: "seller/product/show.html.twig"

app_seller_product_update:
    path: /{id}/edit
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            section: seller
            permission: false
            redirect: referer
            template: "seller/product/update.html.twig"
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
                templates:
                    form: "@SyliusAdmin/Product/_form.html.twig"
                    toolbar: "@SyliusAdmin/Product/Update/_toolbar.html.twig"
                route:
                    name: sylius_admin_product_update
                    parameters:
                      id: $id
                index:
                  route:
                    name: app_seller_product_index

app_seller_product_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.product:deleteAction
        _sylius:
            section: seller
            permission: true
            redirect: referer
            vars:
                icon: trash
          