mapping:
  createdAt: 
    type: int32
  name:
    type: string
  id:
    type: string
  image:
    type: 'string'
  description:
    type: 'string'
  price:
    type: float
  store:
    type: string[]
  rating:
    type: float

