sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

seller_dashboard_product:
  resource: "routes/seller_products.yaml"
  prefix: /seller/stores/{id}/dashboard/products


bitbag_sylius_cms_plugin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"