sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

seller_dashboard_product:
  resource: "routes/seller_products.yaml"
  prefix: /seller/store/products


seller_dashboard_order:
  resource: "routes/seller_orders.yaml"
  prefix: /seller/store/orders


bitbag_sylius_cms_plugin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"