parameters:
    locale: en
    sylius.form.type.product_translation.validation_groups: [app_product]
    sylius.form.type.product.validation_groups: [app_product]
    root_dir: '%kernel.project_dir%'

imports:
  - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services/sitemap_provider.yml" }
  - { resource: "grids/grids.yaml" }
services:
    _defaults:
        autowire: true

        autoconfigure: true

        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

##############Search Config#################################
    App\Infrastructure\Search\Typesense\TypesenseClient:
      arguments:
        $host: '%env(resolve:TYPESENSE_URL)%'
        $apiKey: '%env(TYPESENSE_KEY)%'
  
    App\Infrastructure\Search\Typesense\Command\IndexEntityCommand:
      arguments:
        $root_dir: '%root_dir%'

    App\Infrastructure\GeoLocation\LocationInterface:
      class: App\Infrastructure\GeoLocation\IpinfoLocation
      arguments:
         $token: '%env(IP_INFO_TOKEN)%'

    App\Infrastructure\GeoLocation\IP2GeoLocation:
      arguments:
        $root_dir: '%root_dir%'

    App\Infrastructure\GeoLocation\IpGeoLocation:
      arguments:
        $apiKey: '%env(IP_LOCATION_KEY)%'

    App\Infrastructure\Search\IndexerInterface:
      class: App\Infrastructure\Search\Elasticsearch\ElasticSearchIndexer

    App\Infrastructure\Search\SearchInterface:
      class: App\Infrastructure\Search\Elasticsearch\ElasticSearch
##################End Search Config###########################

    App\ShippingCalculator\ParcelCalculator:
        tags:
            -
                {
                    name: sylius.shipping_calculator,
                    calculator: "parcel",
                    label: "Parcel",
                    form_type: App\Form\Type\ParcelShippingCalculatorType
                }

    app.form.extension.type.customer_profile:
        class: App\Form\Extension\CustomerProfileTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType }
    
    app.factory.product:
        class: App\Factory\ProductFactory
        decorates: sylius.factory.product
        arguments: ['@app.factory.product.inner']
        public: false

    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    app.listener.admin.menu_builder:
        class: App\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems, priority: 1 }